### ISSUE TITLE
Add support for Ubuntu in addition to macOS in setup_custom_fortunes.sh

### ISSUE THREAD

**Issue by laurendc** [heptocat/fortune#17]
Setup script which symlinks custom fortunes currently supports macOS.  Need to add and confirm support for Ubuntu/Debian variants.

**Comment by heptocat** [comment]
The current setup_custom_fortunes.sh works on ubuntu. Will check on nixOS soon

**Comment by laurendc** [comment]
You said that the path to fortunes isn't the same. I confirmed this on a Docker container last night. 

Also, can you confirm the files are being moved with the current script? They shouldn't be. The update that was made to the if condition is now failing because it is supposed to only echo if the executable is not there.

I spent some time testing on a Docker container in Ubuntu last night with this current iteration, and it is failing because the not condition was removed. I have an update I'm working on that should handle changing the path based on OS and I think it should resolve.  

If it is working, perhaps it is a version difference? I would like to replicate this if I can.

**Comment by heptocat** [comment]
The script currently on the master branch is working.
However I did have to mkdir /usr/local/share/games/fortunes first.
Fortune is actually installed under /usr/games/fortune
Version: Ubuntu 18.04.3 LTS

Yes, the custom_fortune files are being copied.

**Comment by laurendc** [comment]
Created a feature branch that should be pushed to remote now & another review request #20

**Comment by laurendc** [comment]
Merged #20, closing this
